server:
  port: 8080
  

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: WELCOME-API
          uri: lb://WELCOME-API
          predicates:
            - Path=/welcome/**

        - id: GREET-API
          uri: lb://GREET-API
          predicates:
            - Path=/greet/**             
       
eureka:
  instance:
    prefer-ip-address: true # To register the microservice in service registry with the IP address instead of host name
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka} 
        

management:
  endpoints:
    web:
      exposure:
        include: '*'   

  boot:
    admin:
      client:
        url: http://localhost:1111/          